'use strict';
const assert = require('node:assert/strict');
const { normalizeConnection } = require('../src/main/modelConfig');
const get = (baseUrl, model = {}) => normalizeConnection({ id: 'test', baseUrl, models: [{ id: 'deepseek-v4-flash', ...model }] }).models[0];
const official = get('https://api.deepseek.com');
assert.equal(official.capabilities.contextWindow, 1048576);
assert.equal(official.capabilities.maxOutputTokens, 384000);
assert.equal(official.capabilities.supportsTools, true);
assert.equal(official.capabilities.supportsStructuredOutput, true);
assert.equal(official.fieldSources.maxOutputTokens, 'models.dev');
assert.notEqual(official.verification.tools, 'ok');
assert.equal(get('https://relay.invalid').capabilities.contextWindow, null);
assert.equal(get('https://api.deepseek.com.evil.invalid').capabilities.contextWindow, null);
assert.equal(get('https://api.deepseek.com', { id: 'deepseek-v4-flash-unknown' }).capabilities.contextWindow, null);
assert.equal(get('https://api.deepseek.com', { capabilities: { contextWindow: 12345 }, fieldSources: { contextWindow: 'provider' } }).capabilities.contextWindow, 12345);
const manual = get('https://api.deepseek.com', { capabilities: { contextWindow: 54321, supportsTools: false, maxOutputTokens: null }, fieldSources: { contextWindow: 'manual', supportsTools: 'manual', maxOutputTokens: 'manual' } });
assert.equal(manual.capabilities.contextWindow, 54321);
assert.equal(manual.capabilities.supportsTools, false);
assert.equal(manual.capabilities.maxOutputTokens, null);
assert.deepEqual(get('https://api.deepseek.com', manual), manual);
console.log('model-metadata: ok (14 checks)');
